version: "3"

services:
  redis:
    container_name: src_redis
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - "redis_data:/bitnami/redis/data"
    ports:
      - "6379:6379"

  src:
    restart: unless-stopped
    container_name: scr
    build: .
    command: daphne -b 0.0.0.0 -p 8000 src.asgi:application
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./media:/app/media
      - ./static:/app/static
      - ./media_cdn:/app/media_cdn
      - ./static_cdn:/app/static_cdn
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - redis

  src_celery:
    container_name: src_celery
    build: .
    command: celery -A src.celery.app worker -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://src_redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
    depends_on:
      - src

  src_beat:
    container_name: src_beat
    build: .
    environment:
      - CELERY_BROKER_URL=redis://src_redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
    command: celery -A src.celery.app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - src
      - src_celery
      - redis

volumes:
  redis_data:
    driver: local
