# Generated by Django 5.2 on 2025-04-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.BigIntegerField(blank=True, default=0.0, null=True),
        ),
    ]
