# Generated by Django 5.2 on 2025-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excell', '0002_alter_card_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
