# Generated by Django 5.2 on 2025-04-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excell', '0003_alter_card_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
