# Generated by Django 5.2 on 2025-04-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=100, unique=True)),
                ('sender_card_number', models.CharField(max_length=16)),
                ('sender_card_expiry', models.CharField(max_length=5)),
                ('sender_phone', models.CharField(max_length=13)),
                ('receiver_card_number', models.CharField(max_length=16)),
                ('receiver_phone', models.CharField(max_length=13)),
                ('sending_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('receiving_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('state', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('try_count', models.IntegerField(default=0)),
                ('otp', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
